### ISSUE TITLE
Check is dead before calling `funcall` on values and `yield_arg` on blocks

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#1336]
`Value` and `Block` structs held in Rust may be unreachable and garbage collected by mruby. Such values are "dead" and have `tt = MRB_TT_FREE`.

Calling a function on a dead value or yielding to a dead block is not likely to end well.

Add a check to these functions for dead values and return a `Fatal` error.

`Value::is_dead` is here: https://github.com/artichoke/artichoke/blob/2d446d307258436f4f63ac4ef8cd644c16d9960e/artichoke-backend/src/value.rs#L107-L113

Checks for dead values should be inserted early here and here:

https://github.com/artichoke/artichoke/blob/2d446d307258436f4f63ac4ef8cd644c16d9960e/artichoke-backend/src/value.rs#L139-L149

https://github.com/artichoke/artichoke/blob/2d446d307258436f4f63ac4ef8cd644c16d9960e/artichoke-backend/src/block.rs#L164-L165

**Comment by stuarth** [comment]
btw @lopopolo this can be closed now unless I'm overlooking something

**Comment by mdesantis** [comment]
Hello! `bundle exec rake spec` told me to write a comment here :eggplant: 

I'm messing around with artichoke for the first time. I just cloned this repository, and installed the build dependencies. I've just ran `bundle exec rake spec`, but it failed:

```
> bundle exec rake spec --trace
** Invoke spec (first_time)
** Execute spec
cargo run -q -- enforced-specs.toml
artichoke 0.1.0-pre.0 (2022-11-16 revision 6417) [x86_64-unknown-linux-gnu]


Array#any? with no block given (a default block of { |x| x } is implicit): ...
Array#any? with a block given: ...
Array#<<: ....
[...] ** many lines that I omitted as I guess they're not useful **
URI.split: .
the URI method: ...S
URI::Util.make_components_hash: .

Passed 1914, skipped 247, not implemented 127, failed 1 specs.

An exception occurred during: kernel_integer
fatal: Value receiver for function call is dead. This indicates a bug in the mruby garbage collector. Please leave a comment at https://github.com/artichoke/artichoke/issues/1336.

(eval):66:in Integer
(eval):66:in Integer
/artichoke/virtual_root/src/lib/core/kernel/Integer_spec.rb:20:in protect
(eval):161:in all?
/artichoke/virtual_root/src/lib/core/kernel/Integer_spec.rb:159
(eval):586:in each
/artichoke/virtual_root/src/lib/spec_runner.rb:74:in run_specs
(eval):1

Passed 1914, skipped 247, not implemented 127, failed 1 specs.
rake aborted!
Command failed with status (1): [cargo run -q -- enforced-specs.toml...]
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/file_utils.rb:67:in `block in create_shell_runner'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/file_utils.rb:57:in `sh'
/home/user/Sviluppo/artichoke/Rakefile:132:in `block (2 levels) in <top (required)>'
/home/user/Sviluppo/artichoke/Rakefile:131:in `chdir'
/home/user/Sviluppo/artichoke/Rakefile:131:in `block in <top (required)>'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/user/.asdf/installs/ruby/3.1.2/bin/rake:25:in `load'
/home/user/.asdf/installs/ruby/3.1.2/bin/rake:25:in `<top (required)>'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `load'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in `run'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in `exec'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/exe/bundle:48:in `block in <top (required)>'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/home/user/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/exe/bundle:36:in `<top (required)>'
/home/user/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `load'
/home/user/.asdf/installs/ruby/3.1.2/bin/bundle:25:in `<main>'
```
If you need more info I'll be happy to help
