### ISSUE TITLE
Panic when calling Rust-implemented methods in core with args that do not match argspec

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#243]
```
>>> match_data = /(?<a>.)(.)(?<b>\d+)(\d)/.match("TñX1138.")
=> #<MatchData "ñX1138" a:"ñ" b:"113">
>>> match_data.end
thread 'main' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:999:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.29/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:214
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/macros.rs:18
  11: core::result::Result<T,E>::expect
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/result.rs:827
  12: core::cell::RefCell<T>::borrow_mut
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libcore/cell.rs:869
  13: artichoke_backend::value::ValueLike::funcall
             at artichoke-backend/src/value.rs:116
  14: <artichoke_backend::Artichoke as artichoke_backend::exception::ExceptionHandler>::last_error
             at artichoke-backend/src/exception.rs:97
  15: <artichoke_backend::Artichoke as artichoke_backend::eval::Eval>::eval
             at artichoke-backend/src/eval.rs:188
  16: artichoke_frontend::repl::run
             at ./artichoke-frontend/src/repl.rs:118
  17: airb::main
             at artichoke-frontend/src/bin/airb.rs:6
  18: std::rt::lang_start::{{closure}}
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:296
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  22: std::panicking::try
             at src/libstd/panicking.rs:275
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  25: std::rt::lang_start
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/libstd/rt.rs:64
  26: airb::main
```

**Comment by lopopolo** [comment]
It looks like this might be caused by mruby unwinding when the a function defined in Rust is called with a non-matching argspec.

**Comment by lopopolo** [comment]
This bug is not specific to `MatchData`.

**Comment by lopopolo** [comment]
mruby does not validate argspecs: https://github.com/mruby/mruby/issues/4688
