### ISSUE TITLE
`Kernel#p` when given no arguments triggers a Rust unsafe precondition violation

### ISSUE THREAD

**Issue by lopopolo** [artichoke/artichoke#2691]
## Fuzzer breakage

The latest run of the fuzz targets have found another trophy:

- https://github.com/artichoke/artichoke/actions/runs/7854703302/job/21435704557 – triggers on this fuzz target:
  ```
  [3.3.0] > [112, 46, 215, 215, 97, 101].map(&:chr).join
  => "p.\xD7\xD7ae"
  ```
  which when invoked, gives an error that indicates that `p` is being called with no arguments:
  ```
  $ ruby -e 'puts [112, 46, 215, 215, 97, 101].map(&:chr).join' | ./target/debug/artichoke
  Traceback (most recent call last):
  (eval):1: undefined method 'ae' (NoMethodError)
  ```
- https://github.com/artichoke/artichoke/actions/runs/7854703302/job/21435704471 – triggers on `artichoke_backend::extn::core::kernel::tests::functional` test:
  https://github.com/artichoke/artichoke/blob/287b1fb132d1cf3bfb4800ac05c7bac6a2a71fd7/artichoke-backend/src/extn/core/kernel/kernel_test.rb#L611-L615

## Reproducer

As of the following nightly, the simplest reproducer is to invoke `p` with no args:

<details>

<summary> nightly version info </summary>

```console
$ RUST_BACKTRACE=1 RUSTFLAGS="-Z sanitizer=address" rustc +nightly -Vv
rustc 1.78.0-nightly (6cc484351 2024-02-10)
binary: rustc
commit-hash: 6cc4843512d613f51ec81aba689180c31b0b28b6
commit-date: 2024-02-10
host: x86_64-apple-darwin
release: 1.78.0-nightly
LLVM version: 17.0.6
```

</details>

```console
$ RUST_BACKTRACE=1 RUSTFLAGS="-Z sanitizer=address" cargo +nightly run --bin artichoke --target x86_64-apple-darwin -- -e 'p'
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/x86_64-apple-darwin/debug/artichoke -e p`
artichoke(83982,0x7ff851972b80) malloc: nano zone abandoned due to inability to reserve vm space.
thread 'main' panicked at library/core/src/panicking.rs:155:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
stack backtrace:
   0: rust_begin_unwind
             at /rustc/6cc4843512d613f51ec81aba689180c31b0b28b6/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_nounwind_fmt::runtime
             at /rustc/6cc4843512d613f51ec81aba689180c31b0b28b6/library/core/src/panicking.rs:110:18
   2: core::panicking::panic_nounwind_fmt
             at /rustc/6cc4843512d613f51ec81aba689180c31b0b28b6/library/core/src/panicking.rs:122:9
   3: core::panicking::panic_nounwind
             at /rustc/6cc4843512d613f51ec81aba689180c31b0b28b6/library/core/src/panicking.rs:155:5
   4: core::slice::raw::from_raw_parts::precondition_check
             at /rustc/6cc4843512d613f51ec81aba689180c31b0b28b6/library/core/src/intrinsics.rs:2634:21
   5: core::slice::raw::from_raw_parts
             at /rustc/6cc4843512d613f51ec81aba689180c31b0b28b6/library/core/src/slice/raw.rs:98:9
   6: artichoke_backend::extn::core::kernel::mruby::kernel_p
             at ./artichoke-backend/src/extn/core/kernel/mruby.rs:69:16
   7: mrb_vm_exec
             at ./artichoke-backend/vendor/mruby/src/vm.c:1792:18
   8: mrb_vm_run
             at ./artichoke-backend/vendor/mruby/src/vm.c:1282:12
   9: mrb_top_run
             at ./artichoke-backend/vendor/mruby/src/vm.c:3112:12
  10: mrb_load_exec
             at ./artichoke-backend/mrbgems/mruby-compiler/core/parse.y:6918:7
  11: mrb_load_nstring_cxt
             at ./artichoke-backend/mrbgems/mruby-compiler/core/parse.y:6990:10
  12: <artichoke_backend::sys::protect::Eval as artichoke_backend::sys::protect::Protect>::run
             at ./artichoke-backend/src/sys/protect.rs:115:9
  13: protect_body
             at ./artichoke-backend/vendor/mruby/mrbgems/mruby-error/src/exception.c:13:10
  14: mrb_protect_error
             at ./artichoke-backend/vendor/mruby/src/vm.c:431:14
  15: mrb_protect
             at ./artichoke-backend/vendor/mruby/mrbgems/mruby-error/src/exception.c:20:10
  16: artichoke_backend::sys::protect::protect
             at ./artichoke-backend/src/sys/protect.rs:46:17
  17: artichoke_backend::sys::protect::eval
             at ./artichoke-backend/src/sys/protect.rs:25:5
  18: artichoke_backend::eval::<impl artichoke_core::eval::Eval for artichoke_backend::artichoke::Artichoke>::eval::{{closure}}
             at ./artichoke-backend/src/eval.rs:27:42
  19: artichoke_backend::artichoke::Artichoke::with_ffi_boundary
             at ./artichoke-backend/src/artichoke.rs:98:26
  20: artichoke_backend::eval::<impl artichoke_core::eval::Eval for artichoke_backend::artichoke::Artichoke>::eval
             at ./artichoke-backend/src/eval.rs:27:13
  21: artichoke_backend::eval::<impl artichoke_core::eval::Eval for artichoke_backend::artichoke::Artichoke>::eval_os_str
             at ./artichoke-backend/src/eval.rs:52:9
  22: artichoke::ruby::execute_inline_eval
             at ./src/ruby.rs:192:23
  23: artichoke::ruby::entrypoint
             at ./src/ruby.rs:150:9
  24: artichoke::ruby::run
             at ./src/ruby.rs:117:18
  25: artichoke::main
             at ./src/bin/artichoke.rs:34:11
  26: core::ops::function::FnOnce::call_once
             at /rustc/6cc4843512d613f51ec81aba689180c31b0b28b6/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread caused non-unwinding panic. aborting.
zsh: abort      RUST_BACKTRACE=1 RUSTFLAGS="-Z sanitizer=address" cargo +nightly run --bin
```

**Comment by lopopolo** [comment]
With the following diff, `count` is clearly correctly getting set to `0`. I believe the issue is that mruby is not making any guarantees about the `args` pointer value if there are indeed no args pushed onto the VM's stack.

```diff
diff --git i/artichoke-backend/src/macros.rs w/artichoke-backend/src/macros.rs
index d888165fae..7b6bc4a78a 100644
--- i/artichoke-backend/src/macros.rs
+++ w/artichoke-backend/src/macros.rs
@@ -422,6 +422,8 @@ macro_rules! mrb_get_args {
             args.as_mut_ptr(),
             count.as_mut_ptr(),
         );
+        dbg!(count.assume_init());
+        dbg!(_argc);
         std::slice::from_raw_parts(args.assume_init(), count.assume_init())
     }};
 }
```

Fixing this should be as simple as returning an empty slice if `count == 0`.
